### PR TITLE
Fix for PyTest6 API: use from_parent rather than constructor

### LINKED ISSUE #9: Incompatibility with pytest 6
This looks to be a warning on pytest 5.x and an error with pytest 6.
```
===================================================================================================================== test session starts =====================================================================================================================
platform linux -- Python 3.8.5, pytest-6.0.1, py-1.9.0, pluggy-0.13.1
rootdir: /home/stuart/Git/parfive, configfile: setup.cfg
plugins: asyncio-0.12.0, socket-0.3.5, cov-2.10.1, localserver-0.5.0, notebook-0.6.0
collected 0 items / 1 error                                                                                                                                                                                                                                   
Coverage.py warning: No data was collected. (no-data-collected)

=========================================================================================================================== ERRORS ============================================================================================================================
_________________________________________________________________________________________________________ ERROR collecting parfive/tests/__init__.py __________________________________________________________________________________________________________
../../.virtualenvs/parfive/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../.virtualenvs/parfive/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../.virtualenvs/parfive/lib/python3.8/site-packages/pluggy/manager.py:84: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
../../.virtualenvs/parfive/lib/python3.8/site-packages/pytest_notebook/plugin.py:257: in pytest_collect_file
    return JupyterNbCollector(path, parent)
../../.virtualenvs/parfive/lib/python3.8/site-packages/_pytest/nodes.py:95: in __call__
    warnings.warn(NODE_USE_FROM_PARENT.format(name=self.__name__), stacklevel=2)
E   pytest.PytestDeprecationWarning: Direct construction of JupyterNbCollector has been deprecated, please use JupyterNbCollector.from_parent.
E   See https://docs.pytest.org/en/stable/deprecations.html#node-construction-changed-to-node-from-parent for more details.

----------- coverage: platform linux, python 3.8.5-final-0 -----------
```

### PR DESCRIPTION
**Pull request by AdamGleave**
Fixes #9 following [PyTest docs](https://docs.pytest.org/en/stable/deprecations.html#node-construction-changed-to-node-from-parent)

### CODE REVIEW

**Comment by AdamGleave** [comment]
Saw test failures from #10 so I have pinned to last supported version of nbconvert. Ideally we'd also support that new API, but I don't understand `nbconvert` well enough to attempt a fix.

**Comment by AdamGleave** [comment]
Also ran into #6, worked around by pinning.

**Comment by AdamGleave** [comment]
@chrisjsewell ready for review

**Comment by chrisjsewell** [comment]
Hey @AdamGleave I hope you don't mind but I took the opportunity to freshen up the repository, and added the pytest 6 in #12

**Comment by AdamGleave** [comment]
No problem -- thanks for fixing the issue!

**Pull request closed without merging**
